
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "horodeski", email = "geovana.horodeski06@gmail.com"},
]
dependencies = [
    "django>=4.2.2",
]
requires-python = ">=3.10"
license = {text = "MIT"}

[tool.pdm.dev-dependencies]
dev = [
    "black>=23.3.0",
]
